### ISSUE TITLE
Scene7 Player is not supporting multiple videos on single page

### ISSUE THREAD

**Issue by sredeker** [amclin/videojs-scene7#10]
Currently, on version 0.7.0, the Videojs-Scene7 player is not functioning properly when there are multiple S7 Adaptive Video Sets on a single page. Clicking play on one video plays that video in the other player. I've confirmed the default Scene7 player works fine with multiple videos. Only the Scene7 video type is having this issue. 

Single S7 AVS - https://www.eaglecreek.com/test/s7-adaptive-video-player-single.html
Multiple S7 AVS - https://www.eaglecreek.com/test/s7-adaptive-video-player-multi.html
Multiple Default Videos - https://www.eaglecreek.com/test/default-video-player-multi.html

**Comment by sredeker** [comment]
PR raised to resolve this issue - https://github.com/amclin/videojs-scene7/pull/11

**Comment by amclin** [comment]
@sredeker this is merged and released as 0.7.1 - can you try that out and see if it fixes your issue?

**Comment by sredeker** [comment]
Thanks for jumping on this but 0.7.1 is not found.
```
npm install                              
npm ERR! code ETARGET
npm ERR! notarget No matching version found for videojs-scene7@^0.7.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by amclin** [comment]
It is published and available on NPMjs.com: https://www.npmjs.com/package/videojs-scene7

You'll need to check your downstream package manager since it sounds like you're not querying NPM directly.
